# Generated by Django 3.0.4 on 2020-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200310_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, choices=[('0', '主管'), ('1', '运维'), ('2', '测试'), ('3', '开发')], max_length=50, null=True, verbose_name='职位'),
        ),
    ]
