# Generated by Django 3.0.4 on 2020-03-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200310_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称'),
        ),
    ]
