# Generated by Django 3.0.4 on 2020-03-21 11:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20200316_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='登录', max_length=64, verbose_name='登录类型: 登录, 登出')),
                ('ip', models.CharField(blank=True, default='', max_length=64, verbose_name='登录ip')),
                ('login_time', models.DateTimeField(default=datetime.datetime(2020, 3, 21, 11, 50, 29, 834038), verbose_name='登录时间')),
                ('status', models.CharField(default='成功', max_length=32, null=True, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='登录用户')),
            ],
        ),
    ]
