# Generated by Django 3.0.4 on 2020-03-18 07:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分组名')),
                ('desc', models.CharField(max_length=32, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房名')),
                ('area', models.CharField(blank=True, max_length=32, verbose_name='区域')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标签名')),
                ('desc', models.CharField(max_length=32, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='公网IP')),
                ('private_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='公网IP')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('fix_number', models.CharField(max_length=64, verbose_name='资产编号')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 3, 18, 15, 35, 57, 644368), verbose_name='添加时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='server', to='cmdb.IDC', verbose_name='机房')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
                ('public_ip', models.CharField(max_length=64, null=True, verbose_name='公网ip')),
                ('private_ip', models.CharField(max_length=64, null=True, verbose_name='私网ip')),
                ('os', models.CharField(default='Linux', max_length=64, verbose_name='操作系统')),
                ('expire', models.DateTimeField(null=True, verbose_name='到期时间')),
                ('type', models.CharField(max_length=64, null=True, verbose_name='类型: 云服务器, 虚拟机')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Group', verbose_name='分组')),
                ('label', models.ManyToManyField(related_name='host', to='cmdb.Label', verbose_name='标签')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Server', verbose_name='宿主机')),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='应用名')),
                ('path', models.CharField(max_length=255, verbose_name='应用路径')),
                ('port', models.CharField(max_length=64, null=True, verbose_name='端口')),
                ('cmd', models.CharField(max_length=255, verbose_name='命令')),
                ('config', models.CharField(max_length=255, null=True, verbose_name='配置文件')),
                ('start', models.CharField(max_length=255, verbose_name='启动')),
                ('stop', models.CharField(max_length=255, verbose_name='停止')),
                ('restart', models.CharField(max_length=255, verbose_name='重启')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Host', verbose_name='宿主机')),
            ],
        ),
    ]
