# Generated by Django 3.0.4 on 2020-03-18 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='管理地址'),
        ),
        migrations.AlterField(
            model_name='server',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 15, 44, 31, 669084), verbose_name='添加时间'),
        ),
    ]
