# Generated by Django 3.0.4 on 2020-03-19 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20200318_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Group', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='host',
            name='label',
            field=models.ManyToManyField(null=True, related_name='host', to='cmdb.Label', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='server',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 13, 54, 46, 356401), verbose_name='添加时间'),
        ),
    ]
