# Generated by Django 3.0.4 on 2020-03-19 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20200319_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='分组名'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='server',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 16, 36, 34, 893345), verbose_name='添加时间'),
        ),
    ]
