# Generated by Django 3.0.4 on 2020-03-19 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0004_auto_20200319_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='host',
        ),
        migrations.AddField(
            model_name='app',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 16, 51, 13, 196451), verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='app',
            name='adder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='app',
            name='log',
            field=models.CharField(max_length=255, null=True, verbose_name='日志'),
        ),
        migrations.AlterField(
            model_name='server',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 16, 51, 13, 193869), verbose_name='添加时间'),
        ),
    ]
